# Generated by Django 4.0.5 on 2022-06-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
