# Generated by Django 4.0.5 on 2022-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_post_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=10000),
        ),
    ]
