# Generated by Django 4.0.5 on 2022-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
